- composer.json
When `installed_paths` is set via a custom, the PHPCS native autoloader cannot find non-sniff files provided by an external standard, including the PHPCSUtils files.
As PHPCS 3.0.2 is rarely used anymore anyway, let's just not support it.
Ref: squizlabs/PHP_CodeSniffer#1591
... to prevent conflicts with projects, be it external standards or end-user projects, which require the plugin themselves as well.
Note: Composer treat minors before `1.0.0` as majors, so each supported minor needs to be explicitly allowed.
Note: Version `0.4.0` is excluded from being installed due to a [bug](Dealerdirect/phpcodesniffer-composer-installer#33) which made it far less usable.
Ref: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases
... as it would block unit testing this repo on …
> Some small improvements to the initial dev setup

- .gitattributes
- .gitignore
- .travis.yml
- PHPCS23Utils/Sniffs/Load/LoadUtilsSniff.php
- PHPCS23Utils/ruleset.xml
- PHPCSUtils/ruleset.xml
- composer.json
- phpcs.xml.dist
- phpcsutils-autoload.php
This PR adds the base rulesets for PHPCSUtils.
It also puts QA in place to:
- Validate the ruleset XML files and verify code style compliance for them.
- Lint PHP files, as the first PHP files are now being introduced into the repo.
- Check the code style of the PHP code.
This will allow PHPCS to recognize PHPCSUtils as if it were an external PHPCS standard and handle the autoloading of all PHPCSUtils files automatically when using PHPCS 3+.
External standards using PHPCSUtils **_don't_** even need to add `<rule ref="PHPCSUtils"/>` to their own ruleset.
All that is needed is for the PHPCSUtils standard to be in the PHPCS `installed_paths` which - for Composer based installs - will automatically be taken care of by the DealerDirect Composer PHPCS plugin which is a `require`d dependency for …
> Add the base rulesets

- .coveralls.yml
- .gitattributes
- .gitignore
- .travis.yml
- PHPCSUtils/BackCompat/Helper.php
- Tests/BackCompat/Helper/ConfigDataTest.php
- Tests/BackCompat/Helper/GetVersionTest.php
- Tests/bootstrap.php
- composer.json
- phpcs.xml.dist
- phpcsutils-autoload.php
- phpunit.xml.dist
Add a `PHPCSUtils\BackCompat\Helper` class for external standards which provides a number of utility functions to help with cross-version compatibility between PHPCS 2.x and PHPCS 3.x.
Initial methods:
* `getVersion()` - get the version number of PHP_CodeSniffer.
* `setConfigData()` - set PHPCS config data.
* `getConfigData()` - get PHPCS config data.
Includes minimal unit tests.
_The initial methods in this class were originally written by me for the external PHPCompatibility & WPCS standards._
-----
As this feature introduces the first unit tests to the repo, the two additional commits sort out the unit test set up and the code coverage monitoring.
----
This:
* Adds a PHPUnit `phpunit.xml.dist` configuration file.
* Adds a `Tests/bootstrap.php` file to load the necessary prerequisites …
> New BackCompat\Helper class (includes unit test setup)

- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- Tests/TestUtils/UtilityMethodTestCase/FailedToTokenizeTest.inc
- Tests/TestUtils/UtilityMethodTestCase/FailedToTokenizeTest.php
- Tests/TestUtils/UtilityMethodTestCase/MissingCaseFileTest.php
- Tests/TestUtils/UtilityMethodTestCase/UtilityMethodTestCaseTest.inc
- Tests/TestUtils/UtilityMethodTestCase/UtilityMethodTestCaseTest.php
- phpcsutils-autoload.php
This `PHPCSUtils\TestUtils\UtilityMethodTestCase` can be used to test arbitrary utility methods written for PHPCS 2.x as well as PHPCS 3.x, using PHPUnit 4.5 - 8.x.
Aside from taking care of setting up PHPCS and tokenizing the test case file, the class offers two utility functions:
* `getTargetToken()` - to get the token pointer for a target token based on a specific comment found on the/a line before. Returns the int stack pointer to the target.
Note: the test delimiter comment MUST start with "/* test" to allow this function to distinguish between comments used *in* a test and test delimiters.
* `expectPhpcsException()` - Helper method to tell PHPUnit to expect a PHPCS Exception in a PHPUnit cross-version compatible manner.
If you choose to use this feature and need to use PHPUnit < 5.4 …
> New `TestUtils\UtilityMethodTestCase`

- PHPCSUtils/BackCompat/Helper.php
- Tests/BackCompat/Helper/GetCommandLineDataTest.inc
- Tests/BackCompat/Helper/GetCommandLineDataTest.php
This adds the following additional methods:
* `getCommandLineData()` - get PHPCS config data which can be overruled from the command line.
* `getTabWidth()` - get the applicable tab width to use.
* `ignoreAnnotations()` - check whether the PHPCS 3.x `--ignore-annotations` option is being used or not.
Includes minimal unit tests.
_The initial methods in this class were originally written by me for the external PHPCompatibility & WPCS standards._
> BackCompat\Helper: add additional PHPCS cross version utility functions

- PHPCSUtils/BackCompat/BCTokens.php
- Tests/BackCompat/BCTokens/ArithmeticTokensTest.php
- Tests/BackCompat/BCTokens/AssignmentTokensTest.php
- Tests/BackCompat/BCTokens/ComparisonTokensTest.php
- Tests/BackCompat/BCTokens/EmptyTokensTest.php
- Tests/BackCompat/BCTokens/FunctionNameTokensTest.php
- Tests/BackCompat/BCTokens/OoScopeTokensTest.php
- Tests/BackCompat/BCTokens/OperatorsTest.php
- Tests/BackCompat/BCTokens/ParenthesisOpenersTest.php
- Tests/BackCompat/BCTokens/TextStringTokensTest.php
- Tests/BackCompat/BCTokens/UnchangedTokenArraysTest.php
PHPCS provides a number of static token arrays in the `PHP_CodeSniffer\Util\Tokens` class.
Some of these token arrays will not be available in older PHPCS versions.
Some will not contain the same set of tokens across PHPCS versions.
The `PHPCSUtils\BackCompat\BCTokens` class is a compatibility layer to allow for retrieving these token arrays with a consistent token content across PHPCS versions.
The one caveat is that the token constants do need to be available.
The class is named `BCTokens` instead of `Tokens` on purpose to more easily allow sniffs to use both the PHPCS native Tokens class as well as this class without always having to alias one of the two.
Recommended usage:
Only use the methods in this class when needed. I.e. when your sniff unit tests indicate a PHPCS cross-version …
> New BackCompat\BCTokens class

- PHPCSUtils/BackCompat/BCFile.php
- Tests/BackCompat/BCFile/FindEndOfStatementTest.inc
- Tests/BackCompat/BCFile/FindEndOfStatementTest.php
- Tests/BackCompat/BCFile/FindExtendedClassNameTest.inc
- Tests/BackCompat/BCFile/FindExtendedClassNameTest.php
- Tests/BackCompat/BCFile/FindImplementedInterfaceNamesTest.inc
- Tests/BackCompat/BCFile/FindImplementedInterfaceNamesTest.php
- Tests/BackCompat/BCFile/GetMemberPropertiesTest.inc
- Tests/BackCompat/BCFile/GetMemberPropertiesTest.php
- Tests/BackCompat/BCFile/GetMethodParametersParseError1Test.inc
- Tests/BackCompat/BCFile/GetMethodParametersParseError1Test.php
- Tests/BackCompat/BCFile/GetMethodParametersParseError2Test.inc
- Tests/BackCompat/BCFile/GetMethodParametersParseError2Test.php
- Tests/BackCompat/BCFile/GetMethodParametersTest.inc
- Tests/BackCompat/BCFile/GetMethodParametersTest.php
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.inc
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.php
- Tests/BackCompat/BCFile/IsReferenceTest.inc
- Tests/BackCompat/BCFile/IsReferenceTest.php
- phpcs.xml.dist
Import the PHPCS native utility methods from the `File` class as per PHPCS 3.5.0, as well as any associated unit tests.
These methods will be improved upon further and - in so far possible - made backward-compatible to allow using the most recent PHPCS versions of these utility methods in older PHPCS version as well.
Copyright of the original code here is held by Squizlabs and the [respective contributors to PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/graphs/contributors).
_Contributors to the specific code imported have been credited and added as co-authors to this commit._
Add author and copyright information for all the imported code.
Note: the names and email addresses used are per the commits made by the contributors to `PHP_CodeSniffer`, which is information in the …
> New BackCompat\BCFile class - import of utilities from phpcs itself

- PHPCSUtils/BackCompat/BCFile.php
- Tests/BackCompat/BCFile/GetConditionTest.inc
- Tests/BackCompat/BCFile/GetConditionTest.php
As the unit tests which have now been added, confirm that there are no cross-version compatibility issues with these methods, there is no need to keep duplicate code around, so fall-back to the PHPCS native methods.
> BCFile::get/hasCondition(): add unit tests

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/Conditions.php
- Tests/BackCompat/BCFile/GetConditionTest.php
- Tests/Utils/Conditions/GetConditionTest.php
New `PHPCSUtils\Utils\Conditions` class which will hold improved versions of the `File::hasCondition()` and the `File::getCondition()` methods as well as additional methods related to examining a `$tokens[$stackPtr]['conditions']` array.
For the initial functions in this class, the unit tests for the `PHPCSUtils\BackCompat\BCFile::getCondition()` and the `PHPCSUtils\BackCompat\BCFile::hasCondition()` functions are re-used to ensure that the improved functions in this class stay compatible with the original functions.
This refactors the `PHPCSUtils\Utils\Conditions::getCondition()` method to be more versatile with an eye on additional methods to be added later.
It also removes duplicate code and will allow the new methods to be added without code duplication.
Includes additional unit tests …
> New Utils\Conditions class

- PHPCSUtils/Utils/Parentheses.php
- Tests/Utils/Parentheses/ParenthesesTest.inc
- Tests/Utils/Parentheses/ParenthesesTest.php
This adds eleven new utility/convenience methods.
The first two are targeted at open/close parentheses tokens:
* `getOwner()` - to retrieve the stack pointer to the parentheses owner of an open/close parenthesis. Returns int or false if the parenthesis does not have an owner.
* `isOwnerIn()` - to check whether the parenthesis owner of an open/close parenthesis is within a limited set of valid owners. Returns bool.
The other eight methods are targeted at arbitrary tokens:
* `hasOwner()` - to check whether the passed token is nested within parentheses owned by one of the valid owners. Returns bool.
* `firstOwnerIn()` - to check whether the owner of the outermost set of parentheses is within a limited set of acceptable tokens. Returns int/false.
* `lastOwnerIn()` - to check whether the owner …
> New Utils\Parentheses class

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/GetTokensAsString.php
- Tests/BackCompat/BCFile/GetTokensAsStringTest.php
- Tests/Utils/GetTokensAsString/GetTokensAsStringTest.php
This adds five new utility/convenience methods which are closely related to the PHPCS native `File::getTokensAsString()` method.
In contrast to the PHPCS native `File::getTokensAsString()` method, which has `$length` as the third parameter, all methods in this class expect a stack pointer to an `$end` token (inclusive) as the third parameter.
Methods:
* `normal()` - to retrieve the tab-replaced content of the tokens from the specified start position in the token stack to the specified end position (inclusive). Returns string.
If the tab width is set, either via a (custom) ruleset, the config file or by passing it on the command-line, PHPCS will automatically replace tabs with spaces.
The `'content'` index key in the `$tokens` array will contain the tab-replaced content.
The …
> New Utils\GetTokensAsString class

- PHPCSUtils/Tokens/Collections.php
New `PHPCSUtils\Tokens\Collections` class which will hold "collections" of related tokens in static properties.
These are additional "token groups" to compliment the ones available through the PHPCS native `\PHP_CodeSniffer\Util\Tokens` class.
These properties are often needed for `register()` methods and/or to disseminate the results of calls to `$phpcsFile->findNext()`/`$phpcsFile->findPrevious()`.
To start off the class, it currently holds the following properties:
* `$closedScopes` - List of tokens which represent "closed" scopes.
* `$OOConstantScopes` - OO scopes in which constants can be declared.
* `$OOPropertyScopes` - OO scopes in which properties can be declared.
The available token collections will grow once more classes get added.
> New Tokens\Collections class

- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
This allows for concrete child classes to set a custom tab width to use for a particular test.
> TestUtils\UtilityMethodTestCase: allow for overruling the default tab width

- PHPCSUtils/Utils/Scopes.php
- Tests/Utils/Scopes/IsOOConstantTest.inc
- Tests/Utils/Scopes/IsOOConstantTest.php
- Tests/Utils/Scopes/IsOOMethodTest.inc
- Tests/Utils/Scopes/IsOOMethodTest.php
- Tests/Utils/Scopes/IsOOPropertyTest.inc
- Tests/Utils/Scopes/IsOOPropertyTest.php
New `PHPCSUtils\Utils\Scopes` class which will hold methods related to the scoping of tokens.
This class is closely related to the `PHPCSUtils\Utils\Conditions` class in that it uses the `$tokens[$stackPtr]['conditions']` index.
This class initially contains the following four utility methods:
* `isOOProperty()` - to check if a `T_VARIABLE` token is a class/trait property. Returns true/false.
* `isOOConstant()` - to check if a `T_CONSTANT` token is a class/interface constant.  Returns true/false.
* `isOOMethod()` - to check if a `T_FUNCTION` token is a class/interface/trait method.  Returns true/false.
* `validDirectScope()` - to check the direct condition of an arbitrary token against a set of valid scope conditions. Returns the integer stackPtr to the direct condition if valid or false …
> New Utils\Scopes class

- PHPCSUtils/BackCompat/BCFile.php
- Tests/BackCompat/BCFile/GetDeclarationNameJSTest.js
- Tests/BackCompat/BCFile/GetDeclarationNameJSTest.php
- Tests/BackCompat/BCFile/GetDeclarationNameTest.inc
- Tests/BackCompat/BCFile/GetDeclarationNameTest.php
In PHPCS 2.x, for JS files, ES6 classes were not tokenized as `T_CLASS`.
This commit adds work-arounds to the utility method to handle the situation correctly.
Ref: squizlabs/PHP_CodeSniffer#1251
In PHPCS 2.x, for JS files, ES6 method were not tokenized as `T_FUNCTION`.
As the `class` condition is not available either in PHPCS 2.x, it will be hard to back-fill this reliably.
For now, I'm making the choice to explicitly **NOT** backfill support for JS ES6 methods in PHPCS < 3.0.0 for the `BCFile::getDeclarationName()` method.
If enough support requests are opened about it, I may reconsider.
Ref: squizlabs/PHP_CodeSniffer#1251
In PHPCS 2.6.0, when live coding, the last token in a file can be tokenized as `T_STRING`, but without having the `content` index key set.
This commit adds a …
> BCFile::getDeclarationName(): add unit tests and fix compatibility with older PHPCS versions

- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/BackCompat/BCFile/FindExtendedClassNameTest.php
- Tests/BackCompat/BCFile/FindImplementedInterfaceNamesTest.php
- Tests/BackCompat/BCFile/GetClassPropertiesTest.php
- Tests/BackCompat/BCFile/GetDeclarationNameTest.php
- Tests/Utils/ObjectDeclarations/FindExtendedClassNameTest.php
- Tests/Utils/ObjectDeclarations/FindImplementedInterfaceNamesTest.php
- Tests/Utils/ObjectDeclarations/GetClassPropertiesTest.php
- Tests/Utils/ObjectDeclarations/GetNameJSTest.php
- Tests/Utils/ObjectDeclarations/GetNameTest.php
New `PHPCSUtils\Utils\ObjectDeclarations` class which will hold improved versions of the `File::getDeclarationName()`, `File::getClassProperties()`, `File::findExtendedClassName()` and the `File::findImplementedInterfaceNames()` methods as well as additional methods related to examining object declaration statements.
For the initial functions in this class, the unit tests for the `PHPCSUtils\BackCompat\BCFile` versions of these functions are re-used to ensure that the improved functions in this class stay compatible with the original functions.
To this end, the pre-existing unit test classes for the `findExtendedClassName()` and `findImplementedInterfaceNames()` methods have been adjusted.
> New Utils\ObjectDeclarations class

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/Utils/ObjectDeclarations/GetNameDiffTest.inc
- Tests/Utils/ObjectDeclarations/GetNameDiffTest.php
While certain names may be invalid, such as construct names starting with a number, for the purpose of alerting users to these invalid names, the `getName()` method should be able to pick up on them.
The `getName()` method has now been adjusted to allow for such names.
The way this has been implemented also improves the parse error resilience for the `getName()` method.
The `getName()` method could previously inadvertently misidentify the name of a structure in the case of parse errors/live coding as it looked for the first `T_STRING` after the keyword without limiting it to the declaration statement. This has now also been fixed.
The method will now return `null`, both when passed  an anonymous class/function as well as in case of a parse error.
Included additional …
> Objectdeclarations::getName(): various improvements

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/Utils/ObjectDeclarations/GetClassPropertiesDiffTest.inc
- Tests/Utils/ObjectDeclarations/GetClassPropertiesDiffTest.php
... as well as handling of unorthodox placement of DocBlocks.
While probably unlikely to come across in the wild, the utility should handle this type of code correctly.
Includes a separate set of unit tests for this method.
These additional tests would fail when using the BCFile version of the method.
A class cannot both be `abstract` as well as `final`, so the utility method should not have to allow for it.
Fixing this makes the utility method more efficient.
* Move the class modifier keywords array to a class property in the `PHPCSUtils\Tokens\Collections` class.
* Declare the `$properties` results array before looping through the tokens.
> ObjectDeclarations::getClassProperties(): various improvements

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/Utils/ObjectDeclarations/FindExtendedClassNameDiffTest.inc
- Tests/Utils/ObjectDeclarations/FindExtendedClassNameDiffTest.php
- Tests/Utils/ObjectDeclarations/FindExtendedClassNameTest.php
- Tests/Utils/ObjectDeclarations/FindImplementedInterfaceNamesDiffTest.inc
- Tests/Utils/ObjectDeclarations/FindImplementedInterfaceNamesDiffTest.php
- Tests/Utils/ObjectDeclarations/FindImplementedInterfaceNamesTest.php
... as well as handling of comments within the class declaration.
While probably unlikely to come across in the wild, the utility should handle this type of code correctly.
Includes a separate set of unit tests for this method.
These additional tests would fail when using the BCFile version of the method.
... as well as handling of comments within the class declaration.
While probably unlikely to come across in the wild, the utility should handle this type of code correctly.
Includes a separate set of unit tests for this method.
These additional tests would fail when using the BCFile version of the method.
As the logic needed for these two methods, as well as for the (upcoming) `findImplementedInterfaces()` method, is basically the same, I've extracted the logic out to a private …
> ObjectDeclarations::findExtendedClassName/findImplementedInterfaceNames(): various improvements

- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/Utils/ObjectDeclarations/FindExtendedInterfaceNamesTest.inc
- Tests/Utils/ObjectDeclarations/FindExtendedInterfaceNamesTest.php
Interfaces can extend more than one interface (in contrast to classes) and both the PHPCS native, as well as  the `Util\ObjectDeclarations` `findExtendedClassName()` method does not allow for that.
See: http://php.net/manual/en/language.oop5.interfaces.php#example-208
To allow for this from within the existing `findExtendedClassName()` method would change the function signature from `@return string|false` to `@return string|array|false`, thus breaking the API.
So, instead, a new `ObjectDeclarations::findExtendedInterfaceNames()` method has been added and it is now explicitly recommended in the documentation of the `findExtendedClassName()` method to use the new method when examining interface declarations.
Includes dedicated unit tests for the new method.
This commit supersedes upstream …
> Util\ObjectDeclarations: add findExtendedInterfaceNames() method

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/Utils/FunctionDeclarations/GetPropertiesDiffTest.inc
- Tests/Utils/FunctionDeclarations/GetPropertiesDiffTest.php
- Tests/Utils/FunctionDeclarations/GetPropertiesTest.php
While probably unlikely to come across in the wild, the utility should handle this type of code correctly.
Includes a separate set of unit tests for this method.
These additional tests would fail when using the BCFile version of the method.
* Move the return type tokens array to a class property in the `PHPCSUtils\Tokens\Collections` class.
* Use the existing `Tokens::$methodPrefixes` token array.
No need to walk the same set of tokens twice to determine whether a function has a body.
We already have the necessary information. Use it.
Also prevents the `has_body` index key from being set to `true` in certain cases of parse errors/live coding.
The `getParameters()` method already returns stack pointers to both the "start" and "end" of a parameter type declaration.
The …
> FunctionDeclarations::getProperties(): various improvements

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/Utils/FunctionDeclarations/GetParametersDiffTest.inc
- Tests/Utils/FunctionDeclarations/GetParametersDiffTest.php
No change in behaviour.
Prevent the method from walking far, far ahead if it would have been passed an import `use` or a trait `use` token.
Once the equal sign has been found, we know that everything else until the end of the parameter is part of the default value.
So instead of looping through each token individually after the equal sign, go straight to the end of the parameter.
This allows for greatly simplifying the code within various `case`s in the `switch` as well as for merging a lot of the `case`s together.
> FunctionDeclarations::getParameters(): various improvements

- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/Utils/FunctionDeclarations/IsMagicFunctionNameTest.php
- Tests/Utils/FunctionDeclarations/IsMagicMethodNameTest.php
- Tests/Utils/FunctionDeclarations/IsPHPDoubleUnderscoreMethodNameTest.php
- Tests/Utils/FunctionDeclarations/SpecialFunctionsTest.inc
- Tests/Utils/FunctionDeclarations/SpecialFunctionsTest.php
Add three new properties related to PHP reserved function names:
* `$magicFunctions`
* `$magicMethods`
* `$methodsDoubleUnderscore`
Also adds eight new utility methods using these properties, for convenience:
* `isMagicFunction()` - to check if the function declared on a `T_FUNCTION` token is a PHP magic function. Returns true/false.
* `isMagicFunctionName()` - to check if a given function name is the name of a PHP magic function. Returns true/false.
* `isMagicMethod()` - to check if the function declared on a `T_FUNCTION` token is a PHP magic method. Returns true/false.
* `isMagicMethodName()` - to check if a given function name is the name of a PHP magic method. Returns true/false.
* `isPHPDoubleUnderscoreMethod()` - to check if the function declared on a `T_FUNCTION` token is a PHP …
> Util\FunctionDeclarations: add new reserved name related utility methods

- PHPCSUtils/Utils/Variables.php
- Tests/BackCompat/BCFile/GetMemberPropertiesTest.php
- Tests/Utils/Variables/GetMemberPropertiesTest.php
New `PHPCSUtils\Utils\Variables` class which will hold an improved version of the `File::getMemberProperties()` method as well as additional methods related to examining variable tokens.
For the initial function in this class, the unit tests for the `PHPCSUtils\BackCompat\BCFile` version of this function are re-used to ensure that the improved function in this class stays compatible with the original function.
> New Utils\Variables class

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Variables.php
- Tests/Utils/Variables/GetMemberPropertiesDiffTest.inc
- Tests/Utils/Variables/GetMemberPropertiesDiffTest.php
- Tests/Utils/Variables/GetMemberPropertiesTest.php
The parse error warning is the purpose of this method, so doesn't belong here.
As an "interface property" is not a valid property, just throw the `$stackPtr is not a class member var` exception instead.
Includes a separate set of unit tests for the changes.
These additional tests would fail when using the BCFile version of the method.
* Move the modifier keywords token array to a class property in the `PHPCSUtils\Tokens\Collections` class.
* Move the property type tokens array to a class property in the `PHPCSUtils\Tokens\Collections` class.
> Variables::getMemberProperties(): various improvements

- PHPCSUtils/Utils/Variables.php
- Tests/Utils/Variables/IsPHPReservedVarNameTest.php
- Tests/Utils/Variables/IsSuperglobalTest.inc
- Tests/Utils/Variables/IsSuperglobalTest.php
Add a new property related to PHP reserved variables names:
* `$phpReservedVars`
Also adds three new utility methods using this property, for convenience:
* `isPHPReservedVarName()` - to check if a given variable name is the name of a PHP reserved variable. Returns true/false.
* `isSuperglobal()` - to check if a given variable or string array key token points to a PHP superglobal. Returns true/false.
* `isSuperglobalName()` - to check if a given variable name is the name of a PHP superglobal variable. Returns true/false.
When passing a `T_CONSTANT_ENCAPSED_STRING` array index token to the `Name` functions, the string quotes around the name should be stripped in advance.
**Note**: I have not currently added a `isPHPReservedVar()` method as a number of the reserved vars are created within a …
> Utils\Variables: add new reserved name related utility methods

- PHPCSUtils/Utils/UseStatements.php
- Tests/Utils/UseStatements/SplitImportUseStatementTest.inc
- Tests/Utils/UseStatements/SplitImportUseStatementTest.php
- Tests/Utils/UseStatements/UseTypeTest.inc
- Tests/Utils/UseStatements/UseTypeTest.php
This introduces five new utility methods to PHPCSUtils.
Methods:
* `getType()` - to determine the type of statement a T_USE token is used for. Returns a string. Either `closure`, `import` or `trait` or an empty string when the type of statement for which it's used could not be determined.
* `isClosureUse()` - Wrapper method to check whether a T_USE token is a closure use statement. Returns boolean.
* `isImportUse()` - Wrapper method to check whether a T_USE token is a class/function/constant import use statement. Returns boolean.
* `isTraitUse()` - Wrapper method to check whether a T_USE token is a trait importing use statement. Returns boolean.
* `splitImportUseStatement()` - to split a multi-import or group-import use statement into information about the individual imports. Returns an …
> New Utils\UseStatements class

- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/Utils/FunctionDeclarations/GetParametersTest.php
... and improve the exception message thrown when a non-closure `T_USE` token was passed.
> FunctionDeclarations::getParameters(): implement use of UseStatements::isClosureUse()

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Namespaces.php
- Tests/Utils/Namespaces/DetermineNamespaceTest.inc
- Tests/Utils/Namespaces/DetermineNamespaceTest.php
- Tests/Utils/Namespaces/GetDeclaredNameTest.inc
- Tests/Utils/Namespaces/GetDeclaredNameTest.php
- Tests/Utils/Namespaces/NamespaceTypeTest.inc
- Tests/Utils/Namespaces/NamespaceTypeTest.php
- phpcs.xml.dist
This introduces six new methods to PHPCSUtils.
Methods:
* `getType()` - to determine what a T_NAMESPACE token is used for. Returns a string. Either `declaration` or `operator` or an empty string when the type of statement for which it's used could not be determined.
* `isDeclaration()` - to check whether a `T_NAMESPACE` token is used to declare a namespace. Returns boolean.
* `isOperator()` - to check whether a `T_NAMESPACE` token is used as an operator. Returns boolean.
* `getDeclaredName()` - to retrieve the (cleaned up) name of a namespace based on the T_NAMESPACE token for the namespace declaration. Returns string|false - the namespace name or an empty string if the code is declared to be in the global namespace. Will return false if the passed token is not for a namespace declaration …
> New Utils\Namespaces class

- PHPCSUtils/Utils/Operators.php
- Tests/BackCompat/BCFile/IsReferenceTest.php
- Tests/Utils/Operators/IsReferenceTest.php
New `PHPCSUtils\Utils\Operators` class which will initially hold an improved version of the `File::isReference()` method as well as, at a later stage, additional methods related to examining operator tokens.
For the initial function in this class, the unit tests for the `PHPCSUtils\BackCompat\BCFile::isReference()` function are re-used to ensure that the improved function in this class stays compatible with the original function.
> New Utils\Operators class

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/Operators.php
- Tests/Utils/Operators/IsReferenceDiffTest.inc
- Tests/Utils/Operators/IsReferenceDiffTest.php
...and remove redundant code from the "is this a function parameter passed by reference" check.
Refs:
* squizlabs/PHP_CodeSniffer#1971
* squizlabs/PHP_CodeSniffer#1284
PHPCS 2.8.0 - 3.2.3 contained a bug where a square open bracket `[` as the first code content after the PHP open tag in a file would be tokenized as `T_OPEN_SQUARE_BRACKET` not `T_OPEN_SHORT_ARRAY`.
This is an edge-case bug as it can only occur when following the very first PHP open tag in a file and only if there is nothing before that open tag.
Either way, this commit adds work-arounds to the utility method to handle the situation correctly.
> Operators::isReference(): various improvements

- PHPCSUtils/Utils/Operators.php
- Tests/Utils/Operators/IsUnaryPlusMinusJSTest.js
- Tests/Utils/Operators/IsUnaryPlusMinusJSTest.php
- Tests/Utils/Operators/IsUnaryPlusMinusTest.inc
- Tests/Utils/Operators/IsUnaryPlusMinusTest.php
* `isUnaryPlusMinus()` - to check whether a plus/minus sign is a unary or an arithmetic operator. Returns boolean.
Includes extensive dedicated unit tests.
The PHP 5.5 `T_YIELD` token was not backfilled in PHPCS until version 3.1.0.
This commit adds work-arounds to the utility method to handle the situation correctly.
Refs:
* squizlabs/PHP_CodeSniffer#1513
* squizlabs/PHP_CodeSniffer#1524
> Utils\Operators: add new isUnaryPlusMinus() utility method

- PHPCSUtils/Utils/Operators.php
- Tests/Utils/Operators/IsShortTernaryTest.inc
- Tests/Utils/Operators/IsShortTernaryTest.php
* `isShortTernary()` - to check whether a ternary then/else operator is part of a short ternary. Returns boolean.
> Utils\Operators: add new isShortTernary() utility method

- PHPCSUtils/Utils/PassedParameters.php
- Tests/Utils/PassedParameters/GetParameterCountTest.inc
- Tests/Utils/PassedParameters/GetParameterCountTest.php
- Tests/Utils/PassedParameters/GetParametersTest.inc
- Tests/Utils/PassedParameters/GetParametersTest.php
- Tests/Utils/PassedParameters/HasParametersTest.inc
- Tests/Utils/PassedParameters/HasParametersTest.php
This introduces four new methods to PHPCSUtils.
These methods are intended for use with:
* `T_STRING` and `T_VARIABLE` tokens for function calls;
* `T_SELF` and `T_STATIC` token for function calls in the form of `new self()`;
* `T_ARRAY` and `T_OPEN_SHORT_ARRAY` tokens for array declarations;
* `T_ISSET` and `T_UNSET` tokens for calls to these language constructs.
Methods:
* `hasParameters()` - to check if parameters have been passed. Returns true/false.
* `getParameters()` - to retrieve details of the passed parameters. Returns an array with `start` (token position), `end` (token position), `raw` (string content) and `clean` (string content without comments) information for each parameter.
* `getParameter()` - to retrieve the details of a specific parameter. Index for the parameters is …
> New Utils\PassedParameters class

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Lists.php
- Tests/Utils/Lists/IsShortListTest.inc
- Tests/Utils/Lists/IsShortListTest.php
- Tests/Utils/Lists/IsShortListTokenizerBC1Test.inc
- Tests/Utils/Lists/IsShortListTokenizerBC1Test.php
- Tests/Utils/Lists/IsShortListTokenizerBC2Test.inc
- Tests/Utils/Lists/IsShortListTokenizerBC2Test.php
* `isShortList()` - to check whether a short array is in actual fact a short list. Returns boolean.
This method has been battle-tested in the past year or so in the PHPCompatibility standard.
This commit also adds two convenience token arrays for working with lists to the `PHPCSUtils\Tokens\Collections` class.
PHPCS 2.8.0 - 3.2.3 contained a bug where a square open bracket `[` as the first code content after the PHP open tag in a file would be tokenized as `T_OPEN_SQUARE_BRACKET` not `T_OPEN_SHORT_ARRAY`.
This is an edge-case bug as it can only occur when following the very first PHP open tag in a file and only if there is nothing before that open tag.
Either way, this commit adds work-arounds to the utility method to handle …
> New Utils\Lists class

- PHPCSUtils/Utils/Lists.php
- Tests/Utils/Lists/GetOpenCloseTest.inc
- Tests/Utils/Lists/GetOpenCloseTest.php
* `getOpenClose()` - to retrieve the open and close brackets for a long/short list in a PHPCS cross-version compatible manner. Returns an array with an 'opener' and a 'closer' key or `false` if not a long/short list.
While this may seem a simple operation, the method will save on code duplication for standards which need to do this in several sniffs.
> Utils\Lists: add new getOpenClose() utility method

- PHPCSUtils/Utils/Lists.php
- Tests/Utils/Lists/GetAssignmentsTest.inc
- Tests/Utils/Lists/GetAssignmentsTest.php
* `getAssignments()` - to retrieve information on the assignments made in the specified (long/short) list. Returns a multi-level array with information on each assignment in the long/short list or an empty array for empty lists.
Includes extensive unit tests.
> Utils\Lists: add new getAssignments() utility method

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- Tests/Utils/Arrays/IsShortArrayTest.inc
- Tests/Utils/Arrays/IsShortArrayTest.php
* `isShortArray()` - to check whether a short array is in actual fact a short array and not a short list. Returns boolean.
This commit also adds two convenience token arrays for working with arrays to the `PHPCSUtils\Tokens\Collections` class.
> New Utils\Arrays class

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- Tests/Utils/Arrays/IsShortArrayTokenizerBC1Test.php
- Tests/Utils/Arrays/IsShortArrayTokenizerBC2Test.php
The PHPCS tokenizer has had a number of issues over the years where the brackets for short arrays were being incorrectly tokenized.
These tests cover those situations.
PHPCS 2.8.0 - 3.2.3 contained a bug where a square open bracket `[` as the first code content after the PHP open tag in a file would be tokenized as `T_OPEN_SQUARE_BRACKET` not `T_OPEN_SHORT_ARRAY`.
This is an edge-case bug as it can only occur when following the very first PHP open tag in a file and only if there is nothing before that open tag.
Either way, this commit adds work-arounds to the utility method to handle the situation correctly.
Includes adding two convenience token arrays for working with arrays in older PHPCS versions to the `PHPCSUtils\Tokens\Collections` class.
Ref: squizlabs/PHP_CodeSniffer#1971
Work …
> Arrays::isShortArray(): fix compatibility with older PHPCS versions

- PHPCSUtils/Utils/PassedParameters.php
- Tests/Utils/PassedParameters/HasParametersTest.inc
- Tests/Utils/PassedParameters/HasParametersTest.php
... by implementing support for passing a `T_OPEN_SQUARE_BRACKET` token, as well as making sure that any `T_OPEN_SHORT_ARRAY` token is actually a short array and not a short list.
> Utils\PassedParameters: fix PHPC cross-version compatibility for short arrays

- PHPCSUtils/Utils/Arrays.php
- Tests/Utils/Arrays/GetOpenCloseTest.inc
- Tests/Utils/Arrays/GetOpenCloseTest.php
* `getOpenClose()` - to retrieve the open and close brackets for a long/short array in a PHPCS cross-version compatible manner. Returns an array with an 'opener' and a 'closer' key or `false` if not a long/short array.
While this may seem a simple operation, the method will save on code duplication for standards which need to do this in several sniffs.
> Utils\Arrays: add new getOpenClose() utility method

- PHPCSUtils/Utils/Arrays.php
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.inc
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.php
* `getDoubleArrowPtr()` - to find the position of a double arrow within an array item. Returns the integer stackPtr position or false if the array item doesn't have a key.
Note: this method will handle nested `foreach` and keyed `yield` structures correctly.
> Utils\Arrays: add new getDoubleArrowPtr() utility method

- PHPCSUtils/Utils/Orthography.php
- Tests/Utils/Orthography/FirstCharTest.php
- Tests/Utils/Orthography/IsLastCharPunctuationTest.php
This class adds three new utility methods for dealing with the contents of arbitrary text strings:
* `isFirstCharCapitalized()` - to check whether the first character of an arbitrary text string is a capital letter. Returns boolean.
* `isFirstCharLowercase()` - to check whether the first character of an arbitrary text string is a lowercase letter. Returns boolean.
* `isLastCharPunctuation()` - to check whether the last character of an arbitrary text string is a punctuation character. By default, the full stop, question mark and exclamation mark are accepted as valid punctuation, but this can easily be changed by passing the `$allowedChars` parameter. Returns boolean.
Ref: https://www.thepunctuationguide.com/terminal-points.html
It also adds a `TERMINAL_POINTS` class constant containing …
> New Utils\Orthography class

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/TextStrings.php
- Tests/Utils/TextStrings/GetCompleteTextStringTest.inc
- Tests/Utils/TextStrings/GetCompleteTextStringTest.php
- Tests/Utils/TextStrings/StripQuotesTest.php
This introduces two new methods:
* `getCompleteTextString()` - to retrieve the complete text string content of a - potentially multi-line - text string. Returns the text string.
* `stripQuotes()` - to strip the text delimiter quotes off an arbitrary text string. Returns the resulting text string.
These methods have been battle-tested in various forms in the past year or two in the PHPCompatibility and the WordPressCS standards.
This commit includes a new convenience token array for working with text strings to the `PHPCSUtils\Tokens\Collections` class.
Includes dedicated unit tests for each method.
> New Utils\TextStrings class

- PHPCSUtils/Utils/Numbers.php
- Tests/Utils/Numbers/GetCompleteNumberTest.inc
- Tests/Utils/Numbers/GetCompleteNumberTest.php
- Tests/Utils/Numbers/GetDecimalValueTest.php
- Tests/Utils/Numbers/NumberTypesTest.php
- composer.json
PHP 7.4 introduced numeric literal separators which break number tokenization in older PHP versions.
PHPCS backfills this since PHPCS 3.5.3, but that backfill implementation is broken in such a bad way that PHPCS 3.5.3 can not be supported.
A fix for the backfill has been merged and will be included in PHPCS 3.5.4.
Having said that, if an external standard intends to support PHPCS < 3.5.3 and/or PHP < 7.4, working with number tokens has become a challenge, as without the backfill any number token is potentially broken
The functions in this class have been put in place to ease that pain and it is *strongly* recommended to always use these functions when sniffing for and/or examining the contents of `T_LNUMBER` or `T_DNUMBER` tokens.
Note: sniffing for `T_STRING` tokens is also affected by …
> New Utils\Numbers class

- Tests/Utils/Operators/IsUnaryPlusMinusTest.inc
- Tests/Utils/Operators/IsUnaryPlusMinusTest.php
... to safeguard that the function will handle these correctly.
> Operators::isUnaryPlusMinus(): add tests with PHP 7.4 numeric literals using underscores

- PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.inc
- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.php
- Tests/AbstractSniffs/AbstractArrayDeclaration/ArrayDeclarationSniffTestDouble.php
- Tests/AbstractSniffs/AbstractArrayDeclaration/GetActualArrayKeyTest.inc
- Tests/AbstractSniffs/AbstractArrayDeclaration/GetActualArrayKeyTest.php
New abstract sniff to examine array declarations.
This abstract sets up a number of helpful properties for the array and then calls the following methods from the `processArray()` method:
* `processOpenClose()` to examine the array opener and closer.
This method will be called independently of whether the array has items or not.
* And then for each individual array item:
- `processKey()` and `processArrow()` for array items with an index key; or `processNoKey()` for array items without one.
- `processValue()`
- `processComma()` (this method _may_ not be called for the last array item if it is not followed by a comma.
Aside from the `process()` method which sets up the properties, all other methods can be overloaded and/or ignored in concrete sniff implementations.
Returning `true` from …
> New `Abstracts\AbstractArrayDeclarationSniff`

- PHPCSUtils/Fixers/SpacesFixer.php
- Tests/Fixers/SpacesFixer/SpacesFixerExceptionsTest.inc
- Tests/Fixers/SpacesFixer/SpacesFixerExceptionsTest.php
- Tests/Fixers/SpacesFixer/SpacesFixerNewlineTest.inc.fixed
- Tests/Fixers/SpacesFixer/SpacesFixerNewlineTest.php
- Tests/Fixers/SpacesFixer/SpacesFixerNoSpaceTest.inc.fixed
- Tests/Fixers/SpacesFixer/SpacesFixerNoSpaceTest.php
- Tests/Fixers/SpacesFixer/SpacesFixerOneSpaceTest.inc.fixed
- Tests/Fixers/SpacesFixer/SpacesFixerOneSpaceTest.php
- Tests/Fixers/SpacesFixer/SpacesFixerTest.inc
- Tests/Fixers/SpacesFixer/SpacesFixerTwoSpaceTest.inc.fixed
- Tests/Fixers/SpacesFixer/SpacesFixerTwoSpaceTest.php
- Tests/Fixers/SpacesFixer/TrailingCommentHandlingTest.inc
- Tests/Fixers/SpacesFixer/TrailingCommentHandlingTest.inc.fixed
- Tests/Fixers/SpacesFixer/TrailingCommentHandlingTest.php
This new class offers one versatile utility function `checkAndFix()` to - as the name implies - check and fix the spacing between two tokens.
It takes all the heavy lifting out of space fixes and should allow standards to get rid of a lot of duplicate code related to space fixing.
Notes:
- This method will not auto-fix if there is anything but whitespace between the two tokens. In that case, it will throw a non-fixable error/warning.
- If 'newline' is expected and _no_ new line is encountered, a new line will be added, but no assumptions will be made about the intended indentation of the code.
This should be handled by a (separate) indentation sniff.
- If 'newline' is expected and multiple new lines are encountered, this will be accepted as valid.
No assumptions are made about whether …
> New Fixers\SpacesFixer class

- .travis.yml
As the tests for this repo do not use the PHPCS native test classes, there is no need for toggling the PHPUnit version.
> Travis: remove redundant condition

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/ControlStructures.php
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError1Test.inc
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError1Test.php
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError2Test.inc
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError2Test.php
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError3Test.inc
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError3Test.php
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError4Test.inc
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseParseError4Test.php
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseTest.inc
- Tests/Utils/ControlStructures/GetDeclareScopeOpenCloseTest.php
- Tests/Utils/ControlStructures/HasBodyParseError1Test.inc
- Tests/Utils/ControlStructures/HasBodyParseError1Test.php
- Tests/Utils/ControlStructures/HasBodyParseError2Test.inc
- Tests/Utils/ControlStructures/HasBodyParseError2Test.php
- Tests/Utils/ControlStructures/HasBodyTest.inc
- Tests/Utils/ControlStructures/HasBodyTest.php
- Tests/Utils/ControlStructures/IsElseIfTest.inc
- Tests/Utils/ControlStructures/IsElseIfTest.php
This adds three new utility methods:
* `hasBody()` - to check whether a control structure has a body and optionally whether that body is non-empty. Returns boolean.
This is a helper function to distinguish between structures like `while (++$i < 10);` and `while (++$i < 10) { /* do something */ }`.
* `isElseIf()` - to check whether an `T_IF` or `T_ELSE` token is part of an `else if`. Returns boolean.
* `getDeclareScopeOpenClose()` - to retrieve the scope open/close pointers for `declare` statements. Returns an array with the stack pointers or false if a file based statement or if the scope open/close pointers could not be determined.
Declare statements come in three flavours:
- file based, without body: `declare(ticks=1);`;
- scoped using curly braces;
- scoped using the alternative …
> New Utils\ControlStructures class

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/Conditions.php
- Tests/BackCompat/BCFile/GetConditionTest.php
- Tests/Utils/Conditions/GetConditionTest.php
PHPCS 3.5.4 introduces a new `$first` parameter to the `File::getCondition()` function.
The PHPCSUtils `Conditions::getCondition()` already had a parameter for the same - `$reverse`, though the boolean values used were also the reverse of how the new `$first` parameter is implemented.
As PHPCSUtils is still in `alpha`, I'm making the executive decision to rename the parameter for the `Conditions::getCondition()`  function to `$first`, including reversing the meaning of the boolean values, to stay in line with PHPCS itself.
* Includes adjusting any and all function calls in the existing codebase for the reversal of the meaning of the boolean.
* Includes moving the unit tests covering this parameter, which were already in place in the test file for the `Conditions::getCondition()` function, …
> BCFile::getCondition()/Conditions::getCondition(): sync with PHPCS 3.5.4 / new $first parameter

- phpcs.xml.dist
…now PHPCS 3.5.4 has been released
> Build/PHPCS: remove temporary exclusion

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/Operators.php
- PHPCSUtils/Utils/Parentheses.php
- Tests/BackCompat/BCFile/FindEndOfStatementTest.inc
- Tests/BackCompat/BCFile/FindEndOfStatementTest.php
- Tests/BackCompat/BCFile/FindStartOfStatementTest.inc
- Tests/BackCompat/BCFile/FindStartOfStatementTest.php
- Tests/BackCompat/BCFile/GetDeclarationNameTest.inc
- Tests/BackCompat/BCFile/GetDeclarationNameTest.php
- Tests/BackCompat/BCFile/GetMethodParametersTest.inc
- Tests/BackCompat/BCFile/GetMethodParametersTest.php
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.inc
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.php
- Tests/BackCompat/BCFile/IsReferenceTest.inc
- Tests/BackCompat/BCFile/IsReferenceTest.php
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.inc
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.php
- Tests/Utils/FunctionDeclarations/GetParametersTest.php
- Tests/Utils/FunctionDeclarations/GetPropertiesTest.php
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.inc
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.php
- Tests/Utils/Parentheses/ParenthesesTest.inc
- Tests/Utils/Parentheses/ParenthesesTest.php
- Tests/Utils/PassedParameters/GetParametersTest.inc
- Tests/Utils/PassedParameters/GetParametersTest.php
This adds support for the PHP 7.4 arrow functions to all relevant utility methods, including back-porting support down to PHPCS 2.6.0 (in as far as possible without the `T_FN` token existing).
These changes are in line with the support for arrow functions as added in PHPCS itself in PHPCS 3.5.3 and 3.5.4.
Also see: squizlabs/PHP_CodeSniffer#2523
To aid both the utility methods in PHPCSUtils as well as sniffs in external standards, two new methods are being introduced:
* `FunctionDeclarations::isArrowFunction()`
* `FunctionDeclarations::getArrowFunctionOpenClose()`
More about both can be found in the below commit summary.
Fixes #3
PHPCS does not adjust the return type token for arrow functions to `T_STRING` until PHPCS 3.5.3/4.
Depening on the PHPCS version and the specific code, an …
> Add support for arrow functions

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/Parentheses.php
- Tests/BackCompat/BCFile/FindEndOfStatementTest.php
- Tests/BackCompat/BCFile/GetMethodParametersTest.inc
- Tests/BackCompat/BCFile/GetMethodParametersTest.php
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.inc
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.php
- Tests/Tokens/Collections/ArrowFunctionTokensBCTest.php
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.inc
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.php
- Tests/Utils/FunctionDeclarations/GetParametersDiffTest.php
- Tests/Utils/FunctionDeclarations/GetParametersTest.php
- Tests/Utils/FunctionDeclarations/GetPropertiesDiffTest.php
- Tests/Utils/FunctionDeclarations/GetPropertiesTest.php
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.inc
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.php
- Tests/Utils/Parentheses/ParenthesesTest.inc
- Tests/Utils/Parentheses/ParenthesesTest.php
Follow up on #77. 
This PR improves the support for arrow functions by:
* Adding a `PHPCSUtils\Tokens\Collections::arrowFunctionTokensBC()` method to retrieve the relevant tokens for the arrow function keyword in a PHPCS cross-version compatible manner.
* Improving the `FunctionDeclarations::isArrowFunction()` and `FunctionDeclarations::getArrowFunctionOpenClose()` to give more informative results.
Previously, they would follow the tokenization to `T_FN` as per PHPCS 3.5.4.
Now they will only return `true` / an array with the token pointers when the token passed actually represents an arrow function keyword token.
- Includes changing the return type of the `FunctionDeclarations::getArrowFunctionOpenClose()` method to `array|false`.
Previously the method would return either an empty array …
> Improve support for arrow functions / sync with phpcs 3.5.5

- Tests/Utils/ControlStructures/IsElseIfTest.php
Three tests were using the wrong test markers.
In effect these three cases were therefore not being tested. Fixed now.
> ControlStructures/IsElseIfTest: bug fix

- Tests/BackCompat/BCFile/FindEndOfStatementTest.php
These are the same changes as pulled upstream in squizlabs/PHP_CodeSniffer 2866
* Use the `AbstractMethodUnitTest::getTargetToken()` method instead of doing a `findNext()` with a calculation.
This makes the `$start` token retrieval more descriptive.
* Assert based on the token pointers, not the sub-array value.
As for both the "expected" as well as "found" values, the token sub-array is retrieved from the same `$tokens` variable, if the token pointers are the same, the sub-arrays will be too, so doing the comparison based on the sub-array doesn't add any extra value to the test.
Also: doing an array assertion is more expensive than doing a simple integer based assertion.
* Remove redundant calls to the `getTokens()` method.
> FindEndOfStatementTest: simplify the tests

- composer.json
The `PHPCSDev` ruleset has been split off from PHPCSDevTools to its own package.
Refs:
* https://github.com/PHPCSStandards/PHPCSDevCS
* PHPCSStandards/PHPCSDevTools#29
> Composer: add PHPCSDevCS dependency

- PHPCSUtils/Utils/Arrays.php
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.inc
- Tests/Utils/Arrays/GetDoubleArrowPtrTest.php
The double arrow directly after a `fn` would be tokenized as `T_STRING` in PHPCS 3.5.4.
Fixed now.
Ref: squizlabs/PHP_CodeSniffer#2865
> Arrays::getDoubleArrowPtr(): work around tokenizer bug in PHPCS 3.5.4

- PHPCSUtils/Utils/Numbers.php
- Tests/Utils/Numbers/GetCompleteNumberTest.php
- Tests/Utils/Operators/IsUnaryPlusMinusTest.php
As the fix for the broken backfill in PHPCS 3.5.3 was released in PHPCS 3.5.4, there is only one PHPCS version which is unsupported.
This negates the need for an array, making it possible to use a class constant instead which should be less risky as it cannot be overloaded.
Includes adjusting all places in the code base which were using the property to use the constant instead.
> Utils\Numbers: replace `$unsupportedPHPCSVersions` with `UNSUPPORTED_VERSION`

- PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.inc
- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.php
Empty array items are not allowed and will trigger a parse error, but the sniff should handle this gracefully.
> AbstractSniffs/AbstractArrayDeclarationSniff: improve handling of parse errors

- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.php
- composer.json
There is only one issue this test suite run into and that is the removal of the `assertAttributeSame()` method.
As for these properties I do deem it important to test the value, I have chosen to emulate the method for PHPUnit 9+.
> PHPUnit: make the tests compatible with PHPUnit 9.x

- composer.json
... as the original appears not to be maintained anymore and is not compatible with PHP 7.4.
> CI: switch to fork of Parallel-lint package

- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- README.md
- docs/index.html
> Document that the TestUtils are compatible with PHPUnit 9.x

- phpcs.xml.dist
Travis clones into a `/home/travis/build/...` directory, so the `build` exclusion for the PHPDoc structure files-only, was now causing all files to be excluded.
Making this exclusion more specific fixes it.
> CI: fix CS check not always running

- phpunit.xml.dist
Bit too strict and too fiddly for my liking.
This reverts commit cf90bbcc895e3c2482aa9f66bb94858deb6050fe.
> Revert "PHPUnit: be strict about covers annotations"

- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- Tests/BackCompat/BCFile/GetDeclarationNameJSTest.php
- Tests/BackCompat/Helper/GetCommandLineDataTest.php
- Tests/Utils/Numbers/GetCompleteNumberTest.php
- Tests/Utils/ObjectDeclarations/GetNameJSTest.php
- Tests/Utils/Operators/IsUnaryPlusMinusTest.php
Tests will often enough need access to the PHPCS version on which the tests are being run.
This adds a `$phpcsVersion` property to the `PHPCSUtils\TestUtils\UtilityMethodTestCase` class to make that version number easily and always available.
**Note**: if the PHPCS version is needed within a data provider method for a test, `Helper::getVersion()` still needs to be used as the data providers are run before the `setUpBeforeClass()` type methods.
... in all relevant places in the existing tests.
> TestUtils\UtilityMethodTestCase: add new $phpcsVersion property

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/Variables.php
- Tests/Tokens/Collections/ParameterTypeTokensBCTest.php
- Tests/Tokens/Collections/PropertyTypeTokensBCTest.php
- Tests/Tokens/Collections/ReturnTypeTokensBCTest.php
:warning: **BREAKING CHANGE** :warning: 
This adds three new methods to the `PHPCSUtils\Tokens\Collections` class:
* `parameterTypeTokensBC()`
* `propertyTypeTokensBC()`
* `returnTypeTokensBC()`
... and adjusts the existing `$parameterTypeTokens`, `$propertyTypeTokens` and `$returnTypeTokens` properties to no longer contain token constants which will be removed in PHPCS 4.x.
As things stands at this time, standards implementing PHPCSUtils which only support PHPCS 3.5.4 or higher, can safely use the properties.
If an external standard wants to continue support for PHPCS < 3.5.4 (return types) or PHPCS < 3.3.0 (parameter and property types), the standard should use the methods instead.
Includes dedicated unit tests for the new methods.
Refs:
* squizlabs/PHP_CodeSniffer@cba0001
This …
> Tokens\Collections: new methods for improved compatibility with PHPCS 4.x

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/ObjectDeclarations.php
PHPCS removes support for the JS and CSS tokenizers, which includes removing the `File::$tokenizerType` property.
This commit makes it so the `BCFile::getDeclarationName()` and the `ObjectDeclarations::getDeclarationName()` methods won't throw an error for the property not existing.
And just to be clear: while PHPCSUtils in combination with PHPCS 2.x and 3.x _may_ incidentally support JS/CSS, in combination with PHPCS 4.x, JS/CSS will explicitly not be supported.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/commit/ea52e7b48165edbcb96b10a0a5de04567e4d73f8
> BCFile/ObjectDeclarations::getDeclarationName(): compatibility with PHPCS 4.x

- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
This implements automatic test skipping for JS/CSS tests on PHPCS 4.x, on which support for JS/CSS has been dropped.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/commit/ea52e7b48165edbcb96b10a0a5de04567e4d73f8
> UtilityMethodTestCase: auto-skip JS/CSS tests when using PHPCS 4.x

- .travis.yml
- Tests/BackCompat/Helper/GetVersionTest.php
- composer.json
Until PHPCS 4.x has been released, PHPCSUtils does not formally support it, though an effort will be made to keep up with the changes and anticipate potential compatibility issues.
For testing purposes, installation of PHPCSUtils with PHPCS 4.x-dev should already be supported though.
Start testing against PHPCS 4.x-dev, for which development has started, to get early warning about cross-version compatibility issues which need fixing.
The build against `4.x-dev` has been added to `allow_failures` for now.
> Composer: allow installation with PHPCS 4.x for testing purposes + Travis test it

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Operators.php
... containing token which can be part of a partially/fully qualified name when used in inline code.
> Tokens\Collections: add $OONameTokens property

- PHPCSUtils/Utils/ControlStructures.php
- Tests/Utils/ControlStructures/GetCaughtExceptionsTest.inc
- Tests/Utils/ControlStructures/GetCaughtExceptionsTest.php
This adds a new utility method to retrieve information on the Exception(s) being caught in a `catch` expression. Returns an array with the `type` (name), `type_token` (start of the name), `type_end_token` for each Exception.
> Utils\ControlStructures: new `getCaughtExceptions()` method

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Operators.php
... containing tokens representing the keywords to access properties or methods from inside a class definition.
Refs:
* https://www.php.net/manual/en/language.oop5.paamayim-nekudotayim.php
* https://www.php.net/manual/en/language.oop5.late-static-bindings.php
> Tokens\Collections: add $OOHierarchyKeywords property

- Tests/AbstractSniffs/AbstractArrayDeclaration/AbstractArrayDeclarationSniffTest.php
- Tests/AssertAttributeSame.php
... to allow use of this functionality in other tests.
At some point in the future this may be (should probably be) abstracted out altogether to a separate package or to the `TestUtils`, but I need to think about that a little more.
For now, setting it up as a `trait` solves the more immediate pressing issue.
> Tests: abstract the assertAttributeSame backfill out to a trait

- PHPCSUtils/Utils/UseStatements.php
- Tests/Utils/UseStatements/SplitAndMergeImportUseStatementTest.inc
- Tests/Utils/UseStatements/SplitAndMergeImportUseStatementTest.php
... which uses the `UseStatements::splitImportUseStatement()` method to retrieve the information on the current `use` import statement and merges the result with an array of previously seen import use statements.
> Utils\UseStatements: add new `splitAndMergeImportUseStatement()` method

- PHPCSUtils/BackCompat/Helper.php
- PHPCSUtils/Utils/Orthography.php
- Tests/BackCompat/Helper/GetCommandLineDataTest.php
... to retrieve the file encoding a project supposedly uses. No check is done to see if the `encoding` set is actually correct for the files presented to PHPCS.
In PHPCS, the `encoding` can be set via `--config-set` or `--encoding` from the command-line or via a custom ruleset like `<arg name="encoding" value="utf-8"/>`.
The default encoding encoding used by PHPCS changed between PHPCS 2.x (`iso-8859-1`) and 3.x `utf-8`.
Using the `utf-8` file encoding is strongly advised for all PHP projects.
Includes minimal unit tests.
> BackCompat\Helper: add `getEncoding()`helper method

- PHPCSUtils/Utils/NamingConventions.php
- Tests/Utils/NamingConventions/IsEqualTest.php
- Tests/Utils/NamingConventions/IsValidIdentifierNameTest.php
.. for working with identifier names (namespace names, class/trait/interface names, function names, variable and constant names).
Initially this class comes with two new utility methods, but the intention is to add a range of additional utilities for common naming conventions (camelCase, snake_case etc) and conversions between those conventions in the near future.
For now, the class contains the following methods:
* `isValidIdentifierName()` - to verify whether an arbitrary text string is valid as an identifier name in PHP. A leading `$` for a variable should be removed prior to passing the name to this method. Returns boolean.
* `isEqual()` - to check if two arbitrary identifier names will be seen as the same in PHP. This method is specifically aimed at the "case-insensitive" (but not …
> New `NamingConventions` class

- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/Utils/FunctionDeclarations/SpecialFunctionsTest.inc
- Tests/Utils/FunctionDeclarations/SpecialFunctionsTest.php
Function declarations nested in a class method declare the function in the global namespace.
See: https://3v4l.org/R32Sl
This was not handled correctly by the function so far. Fixed now.
Includes unit tests covering the fix.
> FunctionDeclarations::isMagicFunction(): bug fix for nested functions

- .travis.yml
The Travis docs say that `$TRAVIS_BUILD_STAGE_NAME` is in "proper case" form:
> TRAVIS_BUILD_STAGE_NAME: The build stage in capitalized form, e.g. Test or Deploy. If a build does not use build stages, this variable is empty ("").
However, it looks like they made an (undocumented) change (probably a bug in their script handling) which means that the `$TRAVIS_BUILD_STAGE_NAME` name is now in the case as given, which in this case is _lowercase_.
This means that some of the comparisons are failing and the wrong things are executed for certain builds.
As I expect this to be a bug in Travis, I'm not changing the case for the comparisons at this time.
Instead I'm fixing this by inline fixing the case of the variable for the comparisons.
Refs:
* …
> Travis: fix the build

- PHPCSUtils/Utils/ObjectDeclarations.php
- Tests/BackCompat/BCFile/GetDeclarationNameTest.inc
- Tests/BackCompat/BCFile/GetDeclarationNameTest.php
> ObjectDeclarations::getName(): bug fix for functions returning by reference

- PHPCSUtils/Utils/Namespaces.php
- Tests/Utils/Namespaces/NamespaceTypeTest.inc
- Tests/Utils/Namespaces/NamespaceTypeTest.php
When the `namespace` keyword is used in the global namespace, it is less easy to determine with 100% certainty whether it used for a declaration or as an operator, especially when taking into account potential coding errors, such as the use of reserved keywords in the namespace name and/or a leading backslash used in a namespace declaration.
This PR hardens the code and will more often correctly detect whether the namespace keyword is used as an operator when used in the global namespace.
> Namespaces::getType(): improve detection of namespace keyword as operator

- PHPCSUtils/Tokens/Collections.php
- Tests/Tokens/Collections/FunctionDeclarationTokensBCTest.php
- Tests/Tokens/Collections/FunctionDeclarationTokensTest.php
* `functionDeclarationTokens()` returning the tokens which can represent a keyword which starts a function declaration.
* `functionDeclarationTokensBC()` same, but allowing for BC down to PHPCS 2.6.0 (arrow functions).
> Tokens\Collections: add two new methods

- PHPCSUtils/Tokens/Collections.php
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.inc
- Tests/BackCompat/BCFile/GetMethodPropertiesTest.php
As of PHP 8.0, `static` can be used as a return type for function declarations.
Ref: https://wiki.php.net/rfc/static_return_type
Includes adding a unit test for the `BCFile::getMethodProperties()`/`FunctionDeclarations::getProperties()` methods to safeguard this.
Sister-PR to the upstream squizlabs/PHP_CodeSniffer#2952
> Tokens\Collections::$returnTypeTokens: allow for "static" (PHP 8)

- composer.json
Support for the `installed_paths` being set when the plugin is a requirement of a standard itself, was only added in version `0.4.0` and a pertinent bug in this feature was fixed in `0.4.1`, which effectively makes version `0.4.1` the minimum workable version for both use as a stand-alone standard, as well as when this standard is required as a dependency.
Refs:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.4.0
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.4.1
> Composer: set minimum Composer PHPCS plugin dependency version to `0.4.1`

- PHPCSUtils/Utils/TextStrings.php
- Tests/Utils/TextStrings/GetCompleteTextStringTest.php
PHP itself does not include the last new line in a heredoc/nowdoc text string when handling it, so this method shouldn't either.
Included adjusted unit tests.
> TextStrings::getCompleteTextString(): remove newline at end of heredoc/nowdoc

- PHPCSUtils/BackCompat/Helper.php
- Tests/BackCompat/Helper/ConfigDataTest.php
- Tests/BackCompat/Helper/GetCommandLineDataTest.php
As of PHPCS 4.x, the `PHP_CodeSniffer\Config::setConfigData()` method is no longer static.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/commit/10a89a2c8c33a26466ccb3368a69a5e99549f80e
This commit adds a new `$config` parameter to the `Helper::setConfigData()` method which will be a required parameter for PHPCS 4.x.
Includes adjusted unit tests.
> Helper::setConfigData(): PHPCS 4.x compatibility

- PHPCSUtils/Utils/ControlStructures.php
- Tests/Utils/ControlStructures/GetCaughtExceptionsTest.inc
- Tests/Utils/ControlStructures/GetCaughtExceptionsTest.php
PHP 8 will introduce non-capturing catch statements.
This tiny fix makes sure the method can handle these correctly.
Ref: https://wiki.php.net/rfc/non-capturing_catches
> ControlStructures::getCaughtExceptions(): add test with PHP8 non-capturing catch

- PHPCSUtils/BackCompat/BCTokens.php
:warning: Breaking Change :warning:
The `$phpcsCommentTokensTypes`, `$ooScopeTokens`, `$textStringTokens` properties all had `protected` visibility.
These properties are not intended to be used directly by implementing standards and with them being `protected`, they would only be accessible if the implementing standard would extend the `BCTokens` class, which doesn't really make sense as it only contains static method anyhow.
So to make the intention clearer, these have now all be reclassified as `private` properties.
> BCTokens: change property visibility

- PHPCSUtils/Utils/Operators.php
- Tests/Utils/Operators/IsReferenceDiffTest.inc
- Tests/Utils/Operators/IsReferenceDiffTest.php
The `&` in a closure declared to return by reference was not recognized as a reference.
Fixed now.
The same fix has also been pulled upstream: squizlabs/php_codesniffer#2977
> Operators::isReference(): bug fix - closure return by reference not recognized

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- Tests/BackCompat/BCFile/FindEndOfStatementTest.inc
- Tests/BackCompat/BCFile/FindEndOfStatementTest.php
- Tests/Utils/FunctionDeclarations/IsArrowFunction2926Test.inc
- Tests/Utils/FunctionDeclarations/IsArrowFunction2926Test.php
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.inc
- Tests/Utils/FunctionDeclarations/IsArrowFunctionTest.php
Follow up on #77 and #79 
This syncs in additional changes from PHPCS upstream as released in PHPCS 3.5.5 and to be released in PHPCS 3.5.6 in the handling and recognition of arrow functions.
Allow for arrow functions being used as function argument as per upstream commit [291401](https://github.com/squizlabs/PHP_CodeSniffer/commit/2914011675cd13f8a7d5eae16ed1d5ee4f0e701d) which is included in PHPCS 3.5.5.
Also see: squizlabs/PHP_CodeSniffer#2895 and squizlabs/PHP_CodeSniffer#2523
Allow for arrow functions being used as function argument as per upstream commit [291401](https://github.com/squizlabs/PHP_CodeSniffer/commit/2914011675cd13f8a7d5eae16ed1d5ee4f0e701d) which is included in PHPCS 3.5.5.
Also see: squizlabs/PHP_CodeSniffer#2895 and squizlabs/PHP_CodeSniffer#2523
... as per upstream …
> Improve support for arrow functions / sync with phpcs 3.5.5/6

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/NamingConventions.php
- PHPCSUtils/Utils/Numbers.php
- PHPCSUtils/Utils/Variables.php
Ref: https://www.php.net/urlhowto.php
> Docs: use language agnostic links to the PHP manual

- PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/BackCompat/BCTokens.php
- PHPCSUtils/BackCompat/Helper.php
- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- PHPCSUtils/Utils/Conditions.php
- PHPCSUtils/Utils/ControlStructures.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/GetTokensAsString.php
- PHPCSUtils/Utils/Lists.php
- PHPCSUtils/Utils/Namespaces.php
- PHPCSUtils/Utils/NamingConventions.php
- PHPCSUtils/Utils/Numbers.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- PHPCSUtils/Utils/Operators.php
- PHPCSUtils/Utils/Orthography.php
- PHPCSUtils/Utils/PassedParameters.php
- PHPCSUtils/Utils/TextStrings.php
- PHPCSUtils/Utils/UseStatements.php
- PHPCSUtils/Utils/Variables.php
* Add additional information.
* Fix incorrect/outdated information.
* Improve information about array return values with specific associative keys.
* Improve specificity of some docs.
* Improve readability of some docs.
* Improve interlinking by adding more `@see` tags.
* Also adding in some more `@link` tags for outside information sources.
> Docs: enhance documentation

- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/FunctionDeclarations.php
Includes moving inline `{@internal}` tags up as they can only be part of the long description as otherwise they are interpreted as meaning the function is _internal_.
> Docs: various tag order fixes

- PHPCSUtils/BackCompat/BCTokens.php
The `BCTokens` class has a `__callStatic()` method to allow for offering methods for all properties from the PHPCS native `Tokens` array, even when they are unchanged.
Using the `@method` tag, it is now documented which methods will magically resolve.
Ref: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#57-method
> Docs: BCTokens: list methods supported

- PHPCSUtils/Utils/ControlStructures.php
- PHPCSUtils/Utils/TextStrings.php
- PHPCSUtils/Utils/UseStatements.php
- PHPCSUtils/Utils/Variables.php
As per the recommendation in [PSR 19](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#514-throws), have one `@throws` tag for each exception thrown, even when they are of the same type.
> Docs: one `@throws` per exception thrown

- PHPCSUtils/AbstractSniffs/AbstractArrayDeclarationSniff.php
- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/BackCompat/BCTokens.php
- PHPCSUtils/BackCompat/Helper.php
- PHPCSUtils/Fixers/SpacesFixer.php
- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/Arrays.php
- PHPCSUtils/Utils/Conditions.php
- PHPCSUtils/Utils/ControlStructures.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/GetTokensAsString.php
- PHPCSUtils/Utils/Lists.php
- PHPCSUtils/Utils/Namespaces.php
- PHPCSUtils/Utils/NamingConventions.php
- PHPCSUtils/Utils/Numbers.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- PHPCSUtils/Utils/Operators.php
- PHPCSUtils/Utils/Orthography.php
- PHPCSUtils/Utils/Parentheses.php
- PHPCSUtils/Utils/PassedParameters.php
- PHPCSUtils/Utils/Scopes.php
- PHPCSUtils/Utils/TextStrings.php
- PHPCSUtils/Utils/UseStatements.php
- PHPCSUtils/Utils/Variables.php
- phpcsutils-autoload.php
* Remove markdown from DocBlock summaries as it's not supported.
* Add backticks around inline code elements in long descriptions and tag descriptions.
* Add markdown where relevant in long descriptions and tag descriptions to improve readability of the rendered output.
* Add inline `{@see ...}` tags to create links to other documented elements.
* Add inline `{@link ...}` tags.
* Replace `<code>` tags with code block syntax.
* Lower the amount of indentation used in code blocks for more readable rendering.
* Replace singular backticks for multi-line code blocks with triple backticks, to allow for rendering as a proper code block instead of inline.
* Replace some semi-lists with list syntax supported via markdown for better rendering.
* Replace some list like return value array definitions …
> Docs: improvements for better rendering in PHPDocumentor

- PHPCSUtils/Utils/ControlStructures.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/ObjectDeclarations.php
- PHPCSUtils/Utils/Variables.php
In a number of places, the specification of an associative array being returned was contained in the long description.
Moving these down to the `@return` tag improves the coherency of the docs.
> Docs: move array return value specs to the `@return` tag

- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/BackCompat/BCTokens.php
- PHPCSUtils/BackCompat/Helper.php
- PHPCSUtils/TestUtils/UtilityMethodTestCase.php
- PHPCSUtils/Tokens/Collections.php
- PHPCSUtils/Utils/ControlStructures.php
- PHPCSUtils/Utils/FunctionDeclarations.php
- PHPCSUtils/Utils/Lists.php
- PHPCSUtils/Utils/NamingConventions.php
- PHPCSUtils/Utils/UseStatements.php
Until 1.0.0 (stable) has been released, it is important to know in which alpha certain things were introduced.
Once 1.0.0 comes out, these should be reverted to read `1.0.0`.
> Docs: update since tags

- CHANGELOG.md
- PHPCSUtils/BackCompat/BCFile.php
- PHPCSUtils/Utils/Operators.php
- Tests/BackCompat/BCFile/IsReferenceTest.inc
- Tests/BackCompat/BCFile/IsReferenceTest.php
- Tests/Utils/Operators/IsReferenceDiffTest.inc
- Tests/Utils/Operators/IsReferenceDiffTest.php
The bugfix for closures declared to return by reference as previously already fixed in the `Operators::isReference()` method, has now also been fixed upstream.
This synces the repo for the upstream fix:
* Apply the fix to the `BCFile::isReference()` method.
* Move the unit test from the test `Diff` file to the `BCFile::isReference()` test case file.
Includes adding a changelog entry to include this in the 1.0.0-alpha3 release.
Refs:
* #142
* squizlabs/php_codesniffer#2977
> BCFile::isReference(): sync with upstream

- CHANGELOG.md
- composer.json
The DealerDirect Composer plugin has just released version `0.7.0`.
As Composer treats minors < 1.0 as majors, updating to this version requires an update to the `composer.json` requirements.
> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.
Refs:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.7.0
* https://getcomposer.org/doc/articles/versions.md#caret-version-range-
> Composer: update PHPCS Composer plugin dependency

- composer.json
* Version 1.2.0 of PHP Parallel Lint has been released.
* Version 0.5 of PHP Console Highlighter has been released.
Especially that last one needs an update to the `composer.json` for it to be allowed to be installed.
> Composer: update dev dependency version allowances
